title: Unnamed Chiori Framework Site
domain: example.com
metatags: []
protected: []
source: /pages
aliases:
  css: /css
  js: /js
  img: /images
database:
  type: mysql
  host: localhost
  port: 3306
  database: chiori
  username: 'fwuser'
  password: 'fwpass'
  prefix: ''
siteID: applebloom