title: Unnamed Chiori Framework Site
domain: example.com
metatags: []
protected: []
source: /pages
aliases:
  css: 'http://css.applebloom.co'
  js: 'http://js.applebloom.co'
  img: 'http://images.applebloom.co'
scripts:
  login-form: 'http://accounts.applebloom.co/login'
  login-post: 'http://accounts.applebloom.co'
login-fields:
  - 'username'
  - 'userID'
  - 'phone'
  - 'email'
database:
  type: mysql
  host: localhost
  port: 3306
  database: chiori
  username: 'fwuser'
  password: 'fwpass'
  prefix: ''
siteID: applebloom